### ISSUE TITLE
Regarding example code on demo page

### ISSUE THREAD

**Issue by jacobStankaitis** [Splidejs/splide-extension-grid#1]
There is an error on the demo page where the example code is written. In the gap array [] should be changed to {}.
**Bad code:**
```
grid       : {
		// You can define rows/cols instead of dimensions.
		dimensions: [ [ 1, 1 ], [ 2, 2 ], [ 2, 1 ], [ 1, 2 ], [ 2, 2 ], [ 3, 2 ] ],
		gap: [
			row: '6px',
			col: '6px',
		],
	},
```
**Fixed code:**
```
grid       : {
		// You can define rows/cols instead of dimensions.
		dimensions: [ [ 1, 1 ], [ 2, 2 ], [ 2, 1 ], [ 1, 2 ], [ 2, 2 ], [ 3, 2 ] ],
		gap: {
			row: '6px',
			col: '6px',
		},
	},
```

**Comment by kostas33** [comment]
Hi there, i figured out the same issue by myself and now i saw this... i  still have a problem with the gaps by the way, even with this fix. Are the gaps ok at your end??

**Comment by jacobStankaitis** [comment]
> Hi there, i figured out the same issue by myself and now i saw this... i still have a problem with the gaps by the way, even with this fix. Are the gaps ok at your end??

I'm not sure, I think I just used custom CSS to fix that.

**Comment by kostas33** [comment]
> 
> 
> > Hi there, i figured out the same issue by myself and now i saw this... i still have a problem with the gaps by the way, even with this fix. Are the gaps ok at your end??
> 
> I'm not sure, I think I just used custom CSS to fix that.

I believe this will be the way for me too.. anyways, thank you

**Comment by NaotoshiFujita** [comment]
I've updated the document. Thanks!
