### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by tjakovcevic** [Splidejs/splide-extension-grid#2]
Can this be used with the react version of splide?

**Comment by NaotoshiFujita** [comment]
React Splide also accepts extensions.
https://splidejs.com/integration/react-splide/#extensions

**Comment by hosseinsarshar** [comment]
@NaotoshiFujita do you have any example on how to integrate it in an app? It's not very clear on how to integrate Grid in a react app from the extensions parameter.

Thanks
